[package]
name = "akakce-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.21.1"
reqwest = { version = "0.12.5", features = ["json"] }
scraper = "0.20.0"
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
